services:
  - type: web
    name: stackhub-backend
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start  
    envVars:
      - key: NODE_ENV
        value: production
      - key: DEPENDENCY_HEALTH_URL
        value: https://dependency-health.onrender.com
      - key: AUTO_TESTS_URL
        value: http://localhost:8001
      - key: PR_REVIEW_URL
        value: http://localhost:8002
    healthCheckPath: /api/status
