# Render.com deployment file for Next.js Backend
# This file is used by Render to deploy the Next.js backend service

# Build Command: ./build.sh
# Start Command: npm start
# Environment: Node.js
# Port: 3000 (default Next.js port)

# Required Environment Variables:
# - DEPENDENCY_HEALTH_URL: URL of the deployed FastAPI dependency health service
# - AUTO_TESTS_URL: URL of the auto-tests service (optional)
# - PR_REVIEW_URL: URL of the PR review service (optional)
# - NODE_ENV: production
